fullnameOverride: "doc-clu-dedup-random-forest-v2"

server:
  autoscale:
    enabled: false
  replicaCount: 3
  args:
  - prod

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    nb.com/external-health-checks:  "http://doc-clu-dedup-random-forest-v2.k8s.nb-prod.com/keepalive"
  hosts:
  - host: doc-clu-dedup-random-forest-v2.k8s.nb-prod.com
    paths:
    - /
